layout_spectrum: 0.507901
typography_spectrum: 0.1459948
color:
  saturation: 0.5770991
  lightness: 0.01162713
  brandStrength: 0.8841959
  rhythmicContrast: 0.5604576
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Peanudt
